# Generated by Django 5.0.3 on 2024-07-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='customer_imgs'),
        ),
    ]
