# Generated by Django 5.0.3 on 2024-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_customer_mobile_customer_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='customer_imgs'),
        ),
    ]
